### ISSUE TITLE
Docs: Add bullet list of what topics are being covered in the Hacking cheatsheet

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [CompassSecurity/Hacking_Tools_Cheat_Sheet#3]
Hi @emanuelduss, @ibuetler 

I read the blogs on your website and found that it has a bulleted list of what topics are there in the cheat sheet. Should I add it in the README.md

Wanted to know your thoughts on this.

Thanks.

Adding the screenshot of the website for reference below =>

![image](https://github.com/CompassSecurity/Hacking_Tools_Cheat_Sheet/assets/63872951/148d5083-6013-45ea-9b04-92f10408c7f4)

**Comment by emanuelduss** [comment]
Hi

I think it's not very important to include this, because the cheat sheet is already quite short and already included in the GitHub readme. So it's already clear what is covered in the cheat sheet. The list was more intended as an introduction to the cheat sheet in the blogpost.

However, if you think it would be useful, you can add it.

Best,
Mänu
